#!/usr/local/bin/python
# -*- coding: utf8 -*-
'''
code generated by dotage on ${TIME}
'''

import pyutil.common.sys_utf8 as utf8
import storage_api.manna_statistic.lib.settings as settings
import storage_api.lib.thing as thing
from pyutil.common.singleton import singleton
@singleton
class ${table_name}(thing.thing):
    def __init__(self, dbproxy, redis):
        self.redis_cache = redis
        self.dbproxy = dbproxy
        self.TABLE_NAME = "${table_name}"
        self.TABLE_ID = "${table_id}"
        self.all = {}
        if settings.LOAD:
            self.load()


if __name__ == '__main__':
    import pyutil.db.mellow as mellow
    import pyconf.db.manna_statistic as manna_statistic
    from pyutil.fb_redis.redis_cache import redis_cache
    import pyconf.redis.redis as redis_conf
    mysql = mellow.mellow(manna_statistic.config)
    redis = redis_cache(config_dic = redis_conf.config)
    print utf8.Utf8(${table_name}(mysql, redis).get(1))
